import React from 'react';
import Link from 'next/link';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div>
        <main className="min-h-screen bg-background flex">
          {children}
        </main>
        </div>
      </body>
    </html>
  )
}