import React from 'react';
import Link from 'next/link';

// interface LayoutProps {
//   children: React.ReactNode;
// }

// const Layout: React.FC<LayoutProps> = ({ children }) => {
//   return (
//     <div className="layout-container">
//       {/* Header Section */}
//       <header className="header">
//         <div className="logo">
//           <img src="public/images/cardinal-logo-transparent.png" alt="Team Logo" />
//         </div>
//         <div className="user">
//         </div>
//         <nav className="navigation">
//           {/* Add navigation items as needed */}
//           <Link href="/upcoming-games">Upcoming Games</Link>
//           <Link href="/news">Latest News</Link>
//         </nav>
//         <div className="search-bar">
//           <input type="text" placeholder="Search for games, players, etc." />
//           <button type="submit">Search</button>
//         </div>
//       </header>

//       {/* Main Content Section */}
//       <main className="main-content">
//         {children}
//       </main>


//       {/* Footer Section for Quick Access to News and Updates */}
//       <footer className="footer">
//         <section className="news-updates">
//           {/* Populate with the latest news and updates about the team */}
//           <h2>Latest News</h2>
//         </section>
//       </footer>
//     </div>
//   );
// };

// export default Layout;

// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  )
}